(function(){'use strict';
const SUPABASE_URL='https://iephgnbxugwaoarwiokn.supabase.co';
const SUPABASE_KEY='sb_publishable_Gi-6hAruqN1R0XCtuInJ-g_2CBfB2jH';
const db=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
let admin=false, currentUser=null, matches=[];
const $=id=>document.getElementById(id);
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function loadPublic(){
 const [{data:players,error:e1},{data:ms,error:e2},{data:rules,error:e3},{data:settings,error:e4}]=await Promise.all([
  db.from('players').select('*').order('points',{ascending:false}),db.from('matches').select('*').order('created_at'),db.from('rules').select('*').order('rule_number'),db.from('site_settings').select('*').eq('id',1).maybeSingle()
 ]);
 if(e1||e2||e3||e4) console.error(e1||e2||e3||e4);
 const s=settings||{};
 $('registrationTitle').textContent=s.registration_title||'Inscrição';$('registrationDescription').textContent=s.registration_description||'Cadastre seu nick e participe do Champions League FM.';$('footerText').textContent=s.footer||'CHAMPIONS LEAGUE FM • YU-GI-OH! FORBIDDEN MEMORIES • TORNEIO ONLINE';$('contactTitle').textContent=s.contact_title||'Contato';$('contactText').textContent=s.contact_text||'';
 $('contactLinks').innerHTML=(s.discord?'<a class="contact-button" href="'+esc(s.discord)+'" target="_blank">DISCORD</a>':'')+(s.twitch?'<a class="contact-button" href="'+esc(s.twitch)+'" target="_blank">TWITCH</a>':'')+(s.whatsapp?'<a class="contact-button" href="'+esc(s.whatsapp)+'" target="_blank">WHATSAPP</a>':'');
 $('rankingBody').innerHTML=(players||[]).map((p,i)=>'<tr><td>'+(i+1)+'</td><td>'+esc(p.nick)+'</td><td>'+p.wins+'</td><td>'+p.losses+'</td><td>'+p.points+'</td></tr>').join('')||'<tr><td colspan="5">Nenhum jogador cadastrado.</td></tr>';
 matches=ms||[];renderMatches();$('rulesList').innerHTML=(rules||[]).map(r=>'<li>'+esc(r.content)+'</li>').join('')||'<li>Nenhuma regra cadastrada.</li>';renderBracket();
}
function renderMatches(){ $('results').innerHTML=matches.map(m=>'<article><small>'+esc(m.status)+'</small><h3>'+esc(m.player1_name||'A definir')+' <b>'+esc(m.score||'—')+'</b> '+esc(m.player2_name||'A definir')+'</h3><small>'+esc(m.round)+'</small></article>').join('')||'<p>Nenhuma partida cadastrada.</p>'; }
function renderBracket(){const R=[['Oitavas de Final',8],['Quartas de Final',4],['Semifinal',2],['Final',1]];$('bracket').innerHTML=R.map(r=>{let ms=matches.filter(x=>x.round===r[0]),out='';for(let i=0;i<r[1];i++){let m=ms[i]||{};out+='<div class="match '+(r[0]==='Final'?'gold':'')+'"><div class="bracket-player">'+esc(m.player1_name||'A definir')+'</div><div class="bracket-score">'+esc(m.score||'—')+'</div><div class="bracket-player">'+esc(m.player2_name||'A definir')+'</div></div>'}return '<div class="bracket-round"><h3>'+r[0].toUpperCase()+'</h3>'+out+'</div>'}).join('');}
async function checkAdmin(){const {data:{user}}=await db.auth.getUser();if(!user)return false;const {data,is_admin}=await db.rpc('is_admin');admin=!!(is_admin===true||data===true);currentUser=user;return admin;}
async function login(){const email=$('adminEmail').value.trim(),password=$('adminPassword').value; $('loginMessage').textContent='Entrando...';const {data,error}=await db.auth.signInWithPassword({email,password});if(error){$('loginMessage').textContent='E-mail ou senha inválidos.';return;}const ok=await checkAdmin();if(!ok){await db.auth.signOut();$('loginMessage').textContent='Este usuário não é administrador.';return;}openPanel();}
function openPanel(){$('loginArea').classList.add('hidden');$('adminArea').classList.remove('hidden');$('adminUser').textContent='Administrador conectado: '+currentUser.email;$('accountEmail').textContent=currentUser.email;fillAdmin();}
async function fillAdmin(){const {data:s}=await db.from('site_settings').select('*').eq('id',1).single();if(s){$('editRegTitle').value=s.registration_title||'';$('editRegDesc').value=s.registration_description||'';$('editFooter').value=s.footer||'';$('editContactTitle').value=s.contact_title||'';$('editContactText').value=s.contact_text||'';$('editDiscord').value=s.discord||'';$('editTwitch').value=s.twitch||'';$('editWhatsapp').value=s.whatsapp||'';}renderPlayersAdmin();renderMatchesAdmin();renderRulesAdmin();}
async function renderPlayersAdmin(){const {data}=await db.from('players').select('*').order('registered_at');$('playersAdmin').innerHTML=(data||[]).map(p=>'<div class="admin-row"><input data-p="'+p.id+'" data-k="nick" value="'+esc(p.nick)+'"><input data-p="'+p.id+'" data-k="discord_whatsapp" value="'+esc(p.discord_whatsapp)+'"><input data-p="'+p.id+'" data-k="twitch" value="'+esc(p.twitch)+'"><input data-p="'+p.id+'" data-k="wins" type="number" value="'+p.wins+'"><input data-p="'+p.id+'" data-k="points" type="number" value="'+p.points+'"><button data-del-p="'+p.id+'" class="danger">EXCLUIR</button></div>').join('')||'<p>Nenhum jogador.</p>';}
async function renderMatchesAdmin(){const {data}=await db.from('matches').select('*').order('created_at');matches=data||[];$('matchesAdmin').innerHTML=matches.map(m=>'<div class="admin-row"><input data-m="'+m.id+'" data-k="round" value="'+esc(m.round)+'"><input data-m="'+m.id+'" data-k="player1_name" value="'+esc(m.player1_name||'')+'"><input data-m="'+m.id+'" data-k="player2_name" value="'+esc(m.player2_name||'')+'"><input data-m="'+m.id+'" data-k="score" value="'+esc(m.score||'—')+'"><input data-m="'+m.id+'" data-k="status" value="'+esc(m.status)+'"><button data-del-m="'+m.id+'" class="danger">EXCLUIR</button></div>').join('')||'<p>Nenhuma partida.</p>';}
async function renderRulesAdmin(){const {data}=await db.from('rules').select('*').order('rule_number');$('rulesAdmin').innerHTML=(data||[]).map(r=>'<div class="rule-row"><input data-r="'+r.id+'" data-k="content" value="'+esc(r.content)+'"><button data-del-r="'+r.id+'" class="danger">×</button></div>').join('');}
async function init(){await loadPublic();$('openAdmin').onclick=()=>$('adminModal').classList.remove('hidden');$('closeAdmin').onclick=()=>$('adminModal').classList.add('hidden');$('loginAdmin').onclick=login;$('adminPassword').addEventListener('keydown',e=>{if(e.key==='Enter')login()});document.querySelectorAll('.admin-tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.admin-tab').forEach(t=>t.classList.add('hidden'));$('tab-'+b.dataset.tab).classList.remove('hidden')});
 $('registrationForm').onsubmit=async e=>{e.preventDefault();const p={nick:$('playerName').value.trim(),discord_whatsapp:$('playerContact').value.trim(),twitch:$('playerTwitch').value.trim()};if(!p.nick||!p.discord_whatsapp||!p.twitch){$('registrationMessage').textContent='Preencha Nick, Discord/WhatsApp e Twitch.';return;}const {error}=await db.from('players').insert(p);if(error){$('registrationMessage').textContent='Não foi possível enviar a inscrição.';console.error(error);return;}e.target.reset();$('registrationMessage').textContent='Inscrição enviada com sucesso!';await loadPublic();if(admin)renderPlayersAdmin();};
 $('saveSite').onclick=async()=>{const {error}=await db.from('site_settings').update({registration_title:$('editRegTitle').value,registration_description:$('editRegDesc').value,footer:$('editFooter').value,updated_at:new Date().toISOString()}).eq('id',1);alert(error?'Erro ao salvar.':'Site atualizado online.');await loadPublic();};
 $('addPlayer').onclick=async()=>{const {error}=await db.from('players').insert({nick:'Novo jogador',discord_whatsapp:'',twitch:''});if(error)alert('Erro: '+error.message);else renderPlayersAdmin();};
 $('addMatch').onclick=async()=>{const {error}=await db.from('matches').insert({round:'Oitavas de Final',player1_name:'A definir',player2_name:'A definir',score:'—',status:'A definir'});if(error)alert('Erro: '+error.message);else{await loadPublic();renderMatchesAdmin();}};
 $('addRule').onclick=async()=>{const {data}=await db.from('rules').select('rule_number').order('rule_number',{ascending:false}).limit(1);const n=(data&&data[0]?data[0].rule_number:0)+1;await db.from('rules').insert({rule_number:n,content:'Nova regra'});renderRulesAdmin();};
 $('saveRules').onclick=async()=>{for(const el of document.querySelectorAll('[data-r][data-k="content"]'))await db.from('rules').update({content:el.value}).eq('id',el.dataset.r);alert('Regras salvas online.');await loadPublic();};
 $('saveContact').onclick=async()=>{const {error}=await db.from('site_settings').update({contact_title:$('editContactTitle').value,contact_text:$('editContactText').value,discord:$('editDiscord').value,twitch:$('editTwitch').value,whatsapp:$('editWhatsapp').value,updated_at:new Date().toISOString()}).eq('id',1);alert(error?'Erro ao salvar.':'Contato atualizado online.');await loadPublic();};
 $('savePassword').onclick=async()=>{const p=$('newPassword').value;if(p.length<6){alert('Use pelo menos 6 caracteres.');return;}const {error}=await db.auth.updateUser({password:p});alert(error?error.message:'Senha alterada com sucesso.');if(!error)$('newPassword').value='';};$('logoutAdmin').onclick=async()=>{await db.auth.signOut();admin=false;currentUser=null;$('adminArea').classList.add('hidden');$('loginArea').classList.remove('hidden');$('adminPassword').value='';};
 $('playersAdmin').onchange=async e=>{const id=e.target.dataset.p,k=e.target.dataset.k;if(!id)return;const v=['wins','points'].includes(k)?Number(e.target.value):e.target.value;const {error}=await db.from('players').update({[k]:v}).eq('id',id);if(error)alert(error.message);await loadPublic();};$('playersAdmin').onclick=async e=>{const id=e.target.dataset.delP;if(id&&confirm('Excluir jogador?')){await db.from('players').delete().eq('id',id);await loadPublic();renderPlayersAdmin();}};
 $('matchesAdmin').onchange=async e=>{const id=e.target.dataset.m,k=e.target.dataset.k;if(!id)return;await db.from('matches').update({[k]:e.target.value}).eq('id',id);await loadPublic();};$('matchesAdmin').onclick=async e=>{const id=e.target.dataset.delM;if(id&&confirm('Excluir partida?')){await db.from('matches').delete().eq('id',id);await loadPublic();renderMatchesAdmin();}};
 $('rulesAdmin').onchange=async e=>{const id=e.target.dataset.r;if(id)await db.from('rules').update({content:e.target.value}).eq('id',id);await loadPublic();};$('rulesAdmin').onclick=async e=>{const id=e.target.dataset.delR;if(id){await db.from('rules').delete().eq('id',id);await loadPublic();renderRulesAdmin();}};
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();