(function(){'use strict';
const U='https://iephgnbxugwaoarwiokn.supabase.co',K='sb_publishable_Gi-6hAruqN1R0XCtuInJ-g_2CBfB2jH';const db=window.supabase.createClient(U,K);const $=id=>document.getElementById(id);const esc=x=>String(x??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const rounds=['Oitavas de Final','Quartas de Final','Semifinal','Final'];
async function isAdmin(){const {data:{user}}=await db.auth.getUser();if(!user)return false;const r=await db.rpc('is_admin');return r.data===true||r.is_admin===true;}
async function render(){if(!(await isAdmin()))return;const {data,error}=await db.from('matches').select('*').order('created_at');if(error){$('matchesAdmin').innerHTML='<p>Erro: '+esc(error.message)+'</p>';return;}const ms=data||[];$('matchesAdmin').innerHTML='<div class="bracket-admin-head"><b>CONFIGURAR VITÓRIAS</b><span>Escolha o vencedor de cada partida. O vencedor avança automaticamente.</span></div>'+rounds.map(r=>{const list=ms.filter(m=>m.round===r);return '<h4>'+r+'</h4>'+(list.map((m,i)=>'<div class="admin-match" data-match="'+m.id+'"><div><b>#'+(i+1)+'</b> '+esc(m.player1_name||'A definir')+' <strong>VS</strong> '+esc(m.player2_name||'A definir')+'</div><label>Placar <input data-score value="'+esc(m.score||'—')+'"></label><button data-winner="1" '+(m.winner_name===m.player1_name?'disabled':'')+'>🏆 VITÓRIA '+esc(m.player1_name||'JOGADOR 1')+'</button><button data-winner="2" '+(m.winner_name===m.player2_name?'disabled':'')+'>🏆 VITÓRIA '+esc(m.player2_name||'JOGADOR 2')+'</button><button data-clear>↩ LIMPAR</button><small>Resultado: '+esc(m.winner_name||'A definir')+'</small></div>').join('')||'<p>Nenhuma partida cadastrada.</p>';}).join('');}
function nextRound(r){const i=rounds.indexOf(r);return i>=0&&i<rounds.length-1?rounds[i+1]:null;}
async function setWinner(id,n){if(!(await isAdmin()))return alert('Acesso de administrador necessário.');const {data:m,error:e}=await db.from('matches').select('*').eq('id',id).single();if(e||!m)return alert(e?.message||'Partida não encontrada.');const winner=n===1?m.player1_name:m.player2_name,loser=n===1?m.player2_name:m.player1_name;if(!winner||winner==='A definir')return alert('Defina os dois jogadores antes de registrar a vitória.');const score=document.querySelector('[data-match="'+id+'"] [data-score]')?.value||m.score||'—';const {error}=await db.from('matches').update({winner_name:winner,score,status:'Finalizada'}).eq('id',id);if(error)return alert('Erro: '+error.message);const ps=await db.from('players').select('id,nick,wins,losses,points').in('nick',[winner,loser]);for(const p of ps.data||[]){const win=p.nick===winner;await db.from('players').update({wins:Number(p.wins||0)+(win?1:0),losses:Number(p.losses||0)+(win?0:1),points:Number(p.points||0)+(win?3:0)}).eq('id',p.id);}
const nr=nextRound(m.round);if(nr){const {data:existing}=await db.from('matches').select('*').eq('round',nr).order('created_at');const same=existing||[];const idx=same.findIndex(x=>!x.player1_name||x.player1_name==='A definir'||!x.player2_name||x.player2_name==='A definir');if(idx>=0){const nm=same[idx];const field=!nm.player1_name||nm.player1_name==='A definir'?'player1_name':'player2_name';await db.from('matches').update({[field]:winner}).eq('id',nm.id);}else{await db.from('matches').insert({round:nr,player1_name:winner,player2_name:'A definir',score:'—',status:'A definir'});}}
await render();if(typeof window.loadPublic==='function')try{await window.loadPublic();}catch(_){location.reload();}}
async function clearWinner(id){if(!(await isAdmin()))return;const {data:m}=await db.from('matches').select('*').eq('id',id).single();if(!m)return;await db.from('matches').update({winner_name:null,status:'A definir'}).eq('id',id);await render();}
function hook(){const tab=document.querySelector('[data-tab="matches"]');if(tab)tab.addEventListener('click',()=>setTimeout(render,50));const box=$('matchesAdmin');if(!box)return;box.addEventListener('click',e=>{const row=e.target.closest('[data-match]');if(!row)return;const id=row.dataset.match;if(e.target.dataset.winner)setWinner(id,Number(e.target.dataset.winner));else if(e.target.dataset.clear)clearWinner(id);});}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',hook);else hook();})();