(function(){'use strict';
const SUPABASE_URL='https://iephgnbxugwaoarwiokn.supabase.co';
const SUPABASE_KEY='sb_publishable_Gi-6hAruqN1R0XCtuInJ-g_2CBfB2jH';
const db=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const rounds=['Oitavas de Final','Quartas de Final','Semifinal','Final'];
async function adminOK(){const {data:{user}}=await db.auth.getUser();if(!user)return false;const r=await db.rpc('is_admin');return r.data===true||r.is_admin===true;}
async function saveWinner(id,n){if(!(await adminOK()))return alert('Acesso de administrador necessário.');const {data:m,error}=await db.from('matches').select('*').eq('id',id).single();if(error||!m)return alert(error?.message||'Partida não encontrada.');const winner=n===1?m.player1_name:m.player2_name;const loser=n===1?m.player2_name:m.player1_name;if(!winner||winner==='A definir'||!loser||loser==='A definir')return alert('Defina os dois jogadores antes de registrar a vitória.');const row=document.querySelector('[data-bracket-match="'+id+'"]');const score=row?.querySelector('[data-bracket-score]')?.value||m.score||'—';let r=await db.from('matches').update({score:score,status:'Finalizada'}).eq('id',id);if(r.error)return alert('Erro ao salvar partida: '+r.error.message);const {data:ps,error:pe}=await db.from('players').select('id,nick,wins,losses,points').in('nick',[winner,loser]);if(pe)return alert('Partida salva, mas erro no ranking: '+pe.message);for(const p of ps||[]){const win=p.nick===winner;r=await db.from('players').update({wins:Number(p.wins||0)+(win?1:0),losses:Number(p.losses||0)+(win?0:1),points:Number(p.points||0)+(win?3:0)}).eq('id',p.id);if(r.error)return alert('Partida salva, mas erro no ranking: '+r.error.message);}
const next=rounds[rounds.indexOf(m.round)+1];if(next){const {data:nm}=await db.from('matches').select('*').eq('round',next).order('created_at');const target=(nm||[]).find(x=>!x.player1_name||x.player1_name==='A definir'||!x.player2_name||x.player2_name==='A definir');if(target){const field=!target.player1_name||target.player1_name==='A definir'?'player1_name':'player2_name';await db.from('matches').update({[field]:winner,status:'A definir'}).eq('id',target.id);}else{await db.from('matches').insert({round:next,player1_name:winner,player2_name:'A definir',score:'—',status:'A definir'});}}
alert('🏆 '+winner+' venceu e avançou!');location.reload();}
async function clearWinner(id){if(!(await adminOK()))return;const {error}=await db.from('matches').update({score:'—',status:'A definir'}).eq('id',id);if(error)return alert(error.message);location.reload();}
function decorate(){const box=document.getElementById('matchesAdmin');if(!box)return;const rows=[...box.querySelectorAll('.admin-row')];rows.forEach(row=>{if(row.dataset.bracketDecorated)return;const id=row.querySelector('[data-m]')?.dataset.m;if(!id)return;row.dataset.bracketDecorated='1';row.dataset.bracketMatch=id;const p1=row.querySelector('[data-k="player1_name"]')?.value||'JOGADOR 1';const p2=row.querySelector('[data-k="player2_name"]')?.value||'JOGADOR 2';const score=row.querySelector('[data-k="score"]');if(score)score.setAttribute('data-bracket-score','');const actions=document.createElement('div');actions.className='bracket-actions';actions.innerHTML='<button type="button" data-win="1">🏆 VITÓRIA '+esc(p1)+'</button><button type="button" data-win="2">🏆 VITÓRIA '+esc(p2)+'</button><button type="button" data-clear-win>↩ LIMPAR RESULTADO</button>';row.appendChild(actions);});}
function init(){const box=document.getElementById('matchesAdmin');if(!box)return;decorate();new MutationObserver(decorate).observe(box,{childList:true,subtree:true});box.addEventListener('click',e=>{const row=e.target.closest('[data-bracket-match]');if(!row)return;const id=row.dataset.bracketMatch;if(e.target.dataset.win)saveWinner(id,Number(e.target.dataset.win));if(e.target.dataset.clearWin)clearWinner(id);});}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();